### ISSUE TITLE
Switch from minio to boto S3 client

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/bioimageio-uploader#22]
This was requested by @oeway.

Initially I picked `minio` as the client, as it seems to an actively developed, higher abstraction / easier interface to S3 compared with `boto3`.

The dependencies are also minimal, having just a small number of basic dependencies,  (https://github.com/minio/minio-py/blob/67aab07025addcccda8d90115279845268bee930/setup.py#L46), while `boto3` is a little heavier despite (supposedly https://github.com/minio/minio-py/issues/560) being a little heavier. 

@oeway, just confirming you still want to me to make this switch (affects a few CI scripts here/the downstream repo)

**Comment by oeway** [comment]
Let's stick to what you have now, and get back when it becomes a real problem. It should be fine for now if you don't use minio specific feature, should work with other implementation of s3.
