### ISSUE TITLE
Add upload progress 

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/bioimageio-uploader#26]
As requested by @oeway in matrix chat

**Comment by jmetz** [comment]
Using `fetch` (https://developer.mozilla.org/en-US/docs/Web/API/fetch), this could be done by passing a `ReadableStream` (https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) to the body, but we would lose some browsers: 
![image](https://github.com/bioimage-io/bioimageio-uploader/assets/1950756/bf8bd1f9-98b8-4071-8103-043d26affba3)
(from: https://developer.mozilla.org/en-US/docs/Web/API/Request#browser_compatibility ) 

AFAIK there are other ways to do this too, using eg `XMLHttpRequest` but requires essentially chunking the upload. 

Maybe this should be a lower priority issue for now - what do you think @oeway ?

**Comment by oeway** [comment]
Would a third party library help? Axio is the one I used in the past.

Seeing an uploading progress would be a really important feature to have, it makes a huge difference in terms of user experience, especially for large/slow model upload.

**Comment by jmetz** [comment]
Yup - as you know I generally prefer "less is more" approach to dependencies to avoid dependency hell, but for this feature it's probably worth it :shrug:

**Comment by jmetz** [comment]
...or I might just use this snippet - https://stackoverflow.com/a/69400632/537098 as it's very probably what's just coded into axios anyway: 

```js
async function main() {
  const blob = new Blob([new Uint8Array(10 * 1024 * 1024)]); // any Blob, including a File
  const uploadProgress = document.getElementById("upload-progress");
  const downloadProgress = document.getElementById("download-progress");

  const xhr = new XMLHttpRequest();
  const success = await new Promise((resolve) => {
    xhr.upload.addEventListener("progress", (event) => {
      if (event.lengthComputable) {
        console.log("upload progress:", event.loaded / event.total);
        uploadProgress.value = event.loaded / event.total;
      }
    });
    xhr.addEventListener("progress", (event) => {
      if (event.lengthComputable) {
        console.log("download progress:", event.loaded / event.total);
        downloadProgress.value = event.loaded / event.total;
      }
    });
    xhr.addEventListener("loadend", () => {
      resolve(xhr.readyState === 4 && xhr.status === 200);
    });
    xhr.open("PUT", "https://httpbin.org/put", true);
    xhr.setRequestHeader("Content-Type", "application/octet-stream");
    xhr.send(blob);
  });
  console.log("success:", success);
}
main().catch(console.error);
```
