### ISSUE TITLE
Enable ImJoy and Hypha api 

### ISSUE THREAD

**Issue by oeway** [bioimage-io/bioimageio-uploader#34]
It will be nice to enable ImJoy API to the uploader so we can open the uploader in an iframe and communicate with the host window. This is important for:
 - in bioimage.io, we can click the edit button on each model card, then allow editing
 - in a jupyter/colab notebook, open it as an ImJoy plugin and pass model yaml and files to the uploader
 - In a command line, python script, napari, etc. we can pass model yaml, files to the uploader interface in the browser.

**Comment by jmetz** [comment]
These are already part of the uploader - see here: 

https://github.com/bioimage-io/bioimageio-uploader/blob/main/src/lib/uploader.ts#L108-L147

Is there something more specific you'd want to happen here?

**Comment by oeway** [comment]
oh nice, but you only setup the imjoy app and hypha server connection, right? To really implement the features, you need to export some api functions in ImJoy and register hypha services so the other tools can call.

**Comment by jmetz** [comment]
Which kind of functions did you want to have enabled? Could you suggest the signatures and I'll fill those in?

**Comment by jmetz** [comment]
Closed with 48a39ba
