### ISSUE TITLE
Add new S3 structure to reflect versions, logs, and comments

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/bioimageio-uploader#37]
As discussed with @FynnBe & @oeway.

Current S3 structure is:

```
model-name/
    status.json
    rdf.yaml
    model files…
``` 

Proposed new structure: 

```
model-name/
    v1/
        status.json    # Containts field "status" with value "staging" or "published" 
        log.json
        comments.json
        files/
            rdf.yaml
            model files…
```

@FynnBe + @oeway - any preference of `files` vs ` data` for the files/data folder?

**Comment by oeway** [comment]
files +1

**Comment by jmetz** [comment]
Asked on matrix: what's the preference for the version-folder naming? 

Here I had v1 to make it clearer, but maybe just "1", "2", etc would suffice?

**Comment by jmetz** [comment]
Partially implemented in https://github.com/bioimage-io/bioimageio-uploader/pull/41

Should now be using log file and new files structure, but these functionalities are untested and only run from CI at present. 

Adding offline testing scripts for these.
