### ISSUE TITLE
Add querying version numbers / getting staging version for a resource

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/bioimageio-uploader#56]
As discussed with @FynnBe , this is likely to require a `versions.json` (or similar) at each resource's root, listing the versions and their publishing status. 

@FynnBe @oeway :

What structure would you think is best for such a file? 

I'm currently thinking: 

```json
{
    "1": "published", 
    "2": "staging", 
}
```

**Comment by FynnBe** [comment]
btw, we should keep the following scenario in mind:
1. user uploads a staged model
2. CI starts testing model
3. user edits staged model
4. CI finishes
5. maintainer sees CI result of outdated version

**Comment by FynnBe** [comment]
one possible solution to this is to use additional status values, but it would be nice to keep it as simple as possible.

**Comment by jmetz** [comment]
So like "testing" - to indicate it's locked for editing or something?

**Comment by jmetz** [comment]
Which would been a user can't edit their staged model until the CI ends.. not ideal, but possibly better than the alternative?

**Comment by jmetz** [comment]
I think we should keep it simple - a user can edit their staged entry, and the fact that that will _possibly_ waste a bit of reviewer time is what it is.. 🤷

**Comment by jmetz** [comment]
This now depends also on https://github.com/bioimage-io/bioimageio-uploader/issues/59

**Comment by jmetz** [comment]
closed with 48a39ba

**Comment by jmetz** [comment]
This was done in https://github.com/bioimage-io/collection
