### ISSUE TITLE
Switch from sandbox to production

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/bioimageio-uploader#67]
hiding-blowfish was staged: https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/hiding-blowfish/versions.json

but the status page for it says "oops": https://bioimageio-uploader.netlify.app/#/status/hiding-blowfish

**Comment by jmetz** [comment]
This should be ready to test using the following: 

* https://bioimageio-uploader.netlify.app/#/uploader/add
* https://bioimageio-uploader.netlify.app/sandbox/#/uploader/add 

ie use the second url to try sandbox mode. This was implemented in #72.
