### ISSUE TITLE
Should there be a link to and from the sandbox mode, and if so, where? 

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/bioimageio-uploader#86]
At the moment, sandbox mode is simply accessed by navigating to "/sandbox" (eg https://deploy-preview-84--bioimageio-uploader.netlify.app/sandbox/#/status). 

This is fine for devs, but if we want this to be a general feature like in zenodo, it might make sense to have a simple link from/to sandbox mode. 

So the questions are: 

1. Should there be such a link? 
2. If so, where should it be? 

For 2. I was thinking that in mobile mode it could be at the bottom of the Hamburger menu, but we don't currently show that in desktop mode... and the equivalent there would be a link on the main Nav, which wouldn't be ideal IMO. 

Thoughts, @oeway + @FynnBe ?

**Comment by FynnBe** [comment]
I think it's fine for devs only.
maybe later we can clean up the treatmeant of sandbox mode a bit and make a unified sandox collection... 
right now those a few flags in different places... we could instead just host a whole sandbox instance (e.g. also as a fork of the current collection repo.. ) such that sandbox runs would also be in a separate place..

**Comment by jmetz** [comment]
> I think it's fine for devs only.
> maybe later we can clean up the treatmeant of sandbox mode a bit and make a unified sandox collection... 
> right now those a few flags in different places... we could instead just host a whole sandbox instance (e.g. also as a fork of the current collection repo.. ) such that sandbox runs would also be in a separate place.. 

Sounds good! You might want to make a corresponding issue in `collection` then I guess - as a placeholder for the changes there, should you decide to go ahead with that. 

For now then, on the UI side, I'll leave it as it is 👍 (unless @oeway disagrees)
